#!/usr/bin/env bash
# Shared helpers for a project's development ecosystem (Plane + Outline + Mailpit).
#
# Sourced, never executed. Deliberately no Python anywhere: this ecosystem lives
# inside the project it serves, so it must contribute nothing to that project's
# own lint and test gates.
#
# Everything generated - the env file, secrets, sync state, backups and Plane's
# vendored bundle - lives under ${INFRA_DIR}/.runtime. That is deliberate: one
# directory for the project to ignore (git) and to exclude (docker build), and a
# single path to check when asking "did anything leak?".
#
# Nothing in this ecosystem writes outside ${INFRA_DIR}; the only files it touches
# in the project itself are the ones the runbook tells you to write by hand.

set -euo pipefail

INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${INFRA_DIR}/.." && pwd)"
RUNTIME_DIR="${INFRA_DIR}/.runtime"
ENV_FILE="${RUNTIME_DIR}/env"
# shellcheck disable=SC2034
PLANE_DIR="${RUNTIME_DIR}/plane-app"
# Read by the scripts that source this file, which shellcheck cannot follow
# across files - hence the disables rather than dead code.
# shellcheck disable=SC2034
SECRETS_DIR="${RUNTIME_DIR}/secrets"
# shellcheck disable=SC2034
STATE_DIR="${RUNTIME_DIR}/state"
# shellcheck disable=SC2034
BACKUP_DIR="${RUNTIME_DIR}/backups"

log()  { printf '%s\n' "  $*"; }
step() { printf '\n==> %s\n' "$*"; }
warn() { printf '%s\n' "warning: $*" >&2; }
die()  { printf '\nERROR: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required but not installed"
}

# The project this ecosystem serves. `git ls-files` is how the docs sync decides
# what to publish, so a checkout is required rather than assumed.
require_project() {
  [ -d "${PROJECT_ROOT}/.git" ] \
    || die "${PROJECT_ROOT} is not a git checkout.
This ecosystem publishes the project's tracked markdown, so the project must be
a repository. Run 'git init' there, or run the scaffold in the right directory."
}

# Load .runtime/env (non-secret runtime configuration) and export it. The file is
# generated by `make env`, and the bootstrap appends what it learns to it.
load_env() {
  [ -f "$ENV_FILE" ] || die "the generated env file is missing - run: make env"
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
  : "${PROJECT_SLUG:?PROJECT_SLUG is not set in ${ENV_FILE}}"
  : "${PROJECT_NAME:=${PROJECT_SLUG}}"
  : "${ECOSYSTEM_HOST:?ECOSYSTEM_HOST is not set in ${ENV_FILE}}"
  : "${ECOSYSTEM_SCHEME:=http}"
  : "${ECOSYSTEM_ADMIN_EMAIL:=admin@example.com}"
  : "${PLANE_VERSION:?PLANE_VERSION is not set in ${ENV_FILE}}"
  : "${PLANE_HTTP_PORT:?PLANE_HTTP_PORT is not set in ${ENV_FILE}}"
  : "${OUTLINE_HTTP_PORT:?OUTLINE_HTTP_PORT is not set in ${ENV_FILE}}"
  : "${MAILPIT_HTTP_PORT:?MAILPIT_HTTP_PORT is not set in ${ENV_FILE}}"
  # Names are derived from the slug so two projects can never collide, and can be
  # overridden in the env file when a project needs to adopt an existing stack.
  : "${SHARED_NETWORK:=${PROJECT_SLUG}-infra}"
  : "${PLANE_COMPOSE_PROJECT:=${PROJECT_SLUG}-plane}"
  : "${MAIL_COMPOSE_PROJECT:=${PROJECT_SLUG}-infra}"
  : "${OUTLINE_COMPOSE_PROJECT:=${PROJECT_SLUG}-outline}"
  : "${MAILPIT_CONTAINER:=${PROJECT_SLUG}-infra-mailpit}"
  : "${PLANE_PROJECT_IDENTIFIER:=${PROJECT_SLUG}}"
  : "${OUTLINE_COLLECTION:=${PROJECT_NAME}}"
  : "${PLANE_EXTERNAL_SOURCE:=${PROJECT_SLUG}-ecosystem}"
  : "${PLANE_HTTPS_PORT:=8443}"
  : "${PLANE_SMTP_PORT_25:=10025}"
  : "${PLANE_SMTP_PORT_465:=10465}"
  : "${PLANE_SMTP_PORT_587:=10587}"
  : "${MAILPIT_SMTP_PORT:=1025}"
  # Mailpit always listens on 1025 *inside* the network; MAILPIT_SMTP_PORT is the
  # port published to the host. Services talking to it container-to-container
  # must use this one - using the host port works only by coincidence, when the
  # probe happens to pick 1025.
  : "${MAIL_INTERNAL_SMTP_PORT:=1025}"
  : "${MAILPIT_VERSION:=v1.31.4}"
  : "${OUTLINE_VERSION:=1.10.1}"
  : "${MAIL_FROM_PLANE:=plane@${PROJECT_SLUG}.local}"
  : "${MAIL_FROM_OUTLINE:=outline@${PROJECT_SLUG}.local}"
  : "${DOCS_EXCLUDE:=ecosystem/}"
  export PROJECT_SLUG PROJECT_NAME ECOSYSTEM_HOST ECOSYSTEM_SCHEME ECOSYSTEM_ADMIN_EMAIL
  export PLANE_VERSION PLANE_HTTP_PORT OUTLINE_HTTP_PORT MAILPIT_HTTP_PORT
  export SHARED_NETWORK PLANE_COMPOSE_PROJECT MAIL_COMPOSE_PROJECT OUTLINE_COMPOSE_PROJECT MAILPIT_CONTAINER
  export PLANE_PROJECT_IDENTIFIER OUTLINE_COLLECTION PLANE_EXTERNAL_SOURCE
  export PLANE_HTTPS_PORT PLANE_SMTP_PORT_25 PLANE_SMTP_PORT_465 PLANE_SMTP_PORT_587
  export MAILPIT_SMTP_PORT MAIL_INTERNAL_SMTP_PORT MAILPIT_VERSION OUTLINE_VERSION MAIL_FROM_PLANE MAIL_FROM_OUTLINE
  export DOCS_EXCLUDE
}

infra_scheme() { printf '%s' "${ECOSYSTEM_SCHEME:-http}"; }
plane_url()   { printf '%s://%s:%s' "$(infra_scheme)" "$ECOSYSTEM_HOST" "$PLANE_HTTP_PORT"; }
outline_url() { printf '%s://%s:%s' "$(infra_scheme)" "$ECOSYSTEM_HOST" "$OUTLINE_HTTP_PORT"; }
mailpit_url() { printf '%s://%s:%s' "$(infra_scheme)" "$ECOSYSTEM_HOST" "$MAILPIT_HTTP_PORT"; }

# Fail early and clearly when a port is already taken. Uses `ss` when available,
# `nc` otherwise.
port_in_use() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -Htln "sport = :${port}" 2>/dev/null | grep -q . && return 0
    return 1
  fi
  command -v nc >/dev/null 2>&1 || return 1
  nc -z 127.0.0.1 "$port" >/dev/null 2>&1
}

check_port_free() {
  local port="$1" what="$2"
  if port_in_use "$port"; then
    die "host port ${port} (${what}) is already in use - change it in ${ENV_FILE} or stop the other process"
  fi
}

# The container publishing a host port, if any.
port_holder() {
  local port="$1"
  docker ps --format '{{.Names}} {{.Ports}}' 2>/dev/null \
    | awk -v p=":${port}->" 'index($0, p) { print $1; exit }'
}

# Installing is meant to be re-runnable, so a port held by OUR OWN container is
# fine (that container is about to be recreated); a port held by anything else is
# not. `ours` is an extended regular expression matched against the name.
check_port_free_or_ours() {
  local port="$1" what="$2" ours="$3" holder
  holder="$(port_holder "$port")"
  if [ -z "$holder" ]; then
    check_port_free "$port" "$what"
    return 0
  fi
  if printf '%s' "$holder" | grep -Eq "$ours"; then
    log "port ${port} (${what}) is held by ${holder} - updating it in place"
    return 0
  fi
  die "host port ${port} (${what}) is held by container ${holder} - change it in ${ENV_FILE} or stop that container"
}

# The first free block of `count` consecutive ports at or above `start`. This is
# how a new project gets its ports: nothing is assumed free, and nothing is
# formula-assigned, because other projects and other services are already here.
find_free_port_block() {
  local start="${1:-8100}" count="${2:-8}" port=0 offset=0
  port="$start"
  while [ "$port" -lt 64000 ]; do
    offset=0
    while [ "$offset" -lt "$count" ]; do
      port_in_use $((port + offset)) && break
      offset=$((offset + 1))
    done
    [ "$offset" -eq "$count" ] && { printf '%s' "$port"; return 0; }
    port=$((port + 1))
  done
  die "no free block of ${count} ports found above ${start}"
}

# Poll a URL until it answers anything other than a connection error.
# args: url, label, timeout-seconds
wait_for_http() {
  local url="$1" label="$2" timeout="${3:-600}" waited=0 code
  step "waiting for ${label} at ${url} (up to ${timeout}s)"
  while [ "$waited" -lt "$timeout" ]; do
    code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "$url" || true)"
    case "$code" in
      2*|3*|4*) log "${label} answered HTTP ${code}"; return 0 ;;
    esac
    sleep 5
    waited=$((waited + 5))
    if [ $((waited % 60)) -eq 0 ]; then log "...still waiting (${waited}s)"; fi
  done
  return 1
}

# Read KEY=value from a file, or print the fallback. One layer of shell quoting
# is stripped: these env files are sourced by bash as well as read here, so any
# value that can contain a space is written quoted.
env_get() {
  local file="$1" key="$2" fallback="${3:-}"
  [ -f "$file" ] || { printf '%s' "$fallback"; return; }
  local value
  value="$(grep -E "^${key}=" "$file" | head -1 | cut -d= -f2- || true)"
  case "$value" in
    \"*\") value="${value#\"}"; value="${value%\"}" ;;
    \'*\') value="${value#\'}"; value="${value%\'}" ;;
  esac
  printf '%s' "${value:-$fallback}"
}

# Set KEY=value in an env-style file, replacing the first match or appending.
set_env_var() {
  local file="$1" key="$2" value="$3" tmp
  tmp="$(mktemp)"
  if grep -qE "^${key}=" "$file"; then
    awk -v k="$key" -v v="$value" '
      BEGIN { done = 0 }
      { if (!done && index($0, k "=") == 1) { print k "=" v; done = 1; next } print }
    ' "$file" > "$tmp"
  else
    cp "$file" "$tmp"
    printf '%s=%s\n' "$key" "$value" >> "$tmp"
  fi
  cat "$tmp" > "$file"
  rm -f "$tmp"
}

# A secret that is safe inside a URL and an env file: hex only.
rand_hex() { openssl rand -hex "${1:-32}"; }

ensure_dir() { mkdir -p "$1"; }

# Load a secrets file and require the named variables.
# args: file, var...
load_secrets() {
  local file="$1"; shift
  [ -f "$file" ] || die "missing ${file} - run the bootstrap (ecosystem/README.md) to create it"
  set -a
  # shellcheck disable=SC1090
  . "$file"
  set +a
  local var
  for var in "$@"; do
    [ -n "${!var:-}" ] || die "${var} is not set in ${file}"
  done
}

# The identity the integrations need, once the bootstrap has learned it.
# Sets PLANE_API_KEY, PLANE_WORKSPACE_SLUG, PLANE_PROJECT_ID.
load_plane_identity() {
  load_secrets "${SECRETS_DIR}/plane.env" PLANE_API_KEY PLANE_WORKSPACE_SLUG PLANE_PROJECT_ID
}

load_outline_token() {
  load_secrets "${SECRETS_DIR}/outline.env" OUTLINE_API_TOKEN
}

# A tiny JSON API helper: sets REPLY_CODE and REPLY_BODY from the response.
# Globals rather than command substitution, because a command substitution runs
# in a subshell and a variable set inside it is lost.
api_call() {
  local method="$1" url="$2" auth="${3:-}" data="${4:-}"
  local args=(-s -X "$method" "$url" -H 'Content-Type: application/json')
  [ -n "$auth" ] && args+=(-H "Authorization: Bearer ${auth}")
  [ -n "$data" ] && args+=(-d "$data")
  local response
  response="$(curl "${args[@]}" -w $'\n%{http_code}')"
  REPLY_CODE="${response##*$'\n'}"
  REPLY_BODY="${response%$'\n'*}"
}

check_reply() {
  local what="$1" want="${2:-200}"
  case "$REPLY_CODE" in
    "$want") return 0 ;;
    "") die "${what}: no answer (connection refused?)" ;;
    429) die "${what}: rate limited (HTTP 429). Wait a minute, or raise the key's rate limit, then re-run." ;;
    *) die "${what}: HTTP ${REPLY_CODE}
$(printf '%s' "$REPLY_BODY" | head -c 400)" ;;
  esac
}
