name: Server Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    server:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [22.x]

        env:
            PERSISTENCE_LOCAL_PATH: .

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build-server
            - run: mkdir tmp # For simulating server restarts
            - run: npm test
            - run: npm run test-gulchdale-acceptance

    docker:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build production Docker image
              run: docker build --tag gulchdale-ci .
